name: ✔ Lint Checks

run-name: 🕵🏻‍♂️ ${{ github.actor }} Running Lint Checks 🕵🏻‍♂️

on:
  push:
    branches:
    - '**'  

jobs: 
  Lint: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version-file: "go.mod"
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
        args: --timeout=30m --new-from-rev=origin/main