name: 🎉 Release

run-name: 🚀 ${{ github.actor }} Building a release 🚀

on:
  push:
    tags:
    - 'v*'  

jobs: 
  Build: 
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
        - name: Checkout
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

        - name: Setup Go
          uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
          with:
            go-version-file: "go.mod"
            cache: true

        - name: Run Unit Tests
          run: make unit-test

        - name: Build
          run: make VERSION=$VERSION build
          env:
            VERSION: ${{  github.ref_name }}

        - name: Run Integration Test
          run: make integration-test

        - name: Uploading artifacts
          uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
          with:
            files: |
              bin/xsh-linux

  Mac-Build: 
    needs: Build
    runs-on: macos-latest
    permissions:
      contents: write
      id-token: write
    steps:
        - name: Checkout
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

        - name: Setup Go
          uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417
          with:
            go-version-file: "go.mod"
            cache: true

        - name: Build
          run: make VERSION=$VERSION build
          env:
            VERSION: ${{ github.ref_name }}

        - name: Run Integration Test
          run: make integration-test

        - name: Uploading artifacts
          uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
          with:
            files: |
              bin/xsh-mac